### ISSUE TITLE
!country [username] returns wrong country

### ISSUE THREAD

**Issue by dbav** [professor-l/classic-tetris-project#37] opened 2020-08-04 15:20 UTC
Using !country [username] should return the country of the specified user, however, it returns the country of the user that typed the message.

**Comment by alex-ong** [comment] 2020-08-04 22:56
This is intended behavior. !country username returns the country that the person who typed it wants the user to move to.

:Kappa:

**Comment by hydra314** [comment] 2020-08-06 06:12
The !country [username] command also pings the subject of the command, which is inconsistent with how other commands of this nature work.

**Comment by alex-ong** [comment] 2020-08-06 09:06
@hydra314 this is working as intended, so that the subject is notified that their current visa has expired and to move to the requestors country

**Comment by hydra314** [comment] 2020-08-06 09:20
![image](https://user-images.githubusercontent.com/11010760/89514729-10c51980-d78b-11ea-916a-6f8abf2954c2.png)
The absolute scenes when Batfoy returns to his home country of Mongolia with the CTWC 2020 trophy

**Comment by vansh09122003** [comment] 2020-09-15 08:39
its not ntworking
ferrow is from germany
![Screenshot (33)](https://user-images.githubusercontent.com/49370661/93187077-0409ed00-f75d-11ea-932b-eb96a763a7eb.png)

**Comment by fractal161** [comment] 2024-05-22 05:46
resolved in https://github.com/professor-l/classic-tetris-project/commit/36bca2cefe01876530207cadae5ac40766066dd6.

**Closed by fractal161** 2024-05-22 05:46 UTC
